In [ ]:
# Convert 1D Array to 2D
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, 3)
print(arr_2d)


[[1 2 3]
 [4 5 6]]


In [ ]:
#print array attributes 
arr = np.array([[10, 20, 30], [40, 50, 60]])
print("Shape:", arr.shape)
print("Dimension:", arr.ndim)
print("Data Type:", arr.dtype)
print("Item Size:", arr.itemsize)


Shape: (2, 3)
Dimension: 2
Data Type: int64
Item Size: 8


In [ ]:
# Create a 3×3 Array of All 9s
arr = np.full((3, 3), 9)
print(arr)


[[9 9 9]
 [9 9 9]
 [9 9 9]]


In [ ]:
#1D Array of 10 Evenly Spaced Values (25 to 125)
linspace_arr = np.linspace(25, 125, 10)
print(linspace_arr)


[ 25.          36.11111111  47.22222222  58.33333333  69.44444444
  80.55555556  91.66666667 102.77777778 113.88888889 125.        ]


In [ ]:
#Convert a Python List into a NumPy Array
py_list = [10, 20, 30, 40, 50]
np_arr = np.array(py_list)
print(np_arr)


[10 20 30 40 50]


In [ ]:
#Reverse a 1D NumPy Array
orig_arr = np.array([1, 2, 3, 4, 5])
reversed_arr = orig_arr[::-1]
print(reversed_arr)


[5 4 3 2 1]


In [ ]:
#Extract Value from 4×4×3 Array (2nd Set, 1st Row, Last Column)
arr_3d = np.arange(4 * 4 * 3).reshape(4, 4, 3)
extracted_val = arr_3d[1, 0, -1]
print(extracted_val)


14


In [ ]:
#Extract Odd Rows and Even Columns from a 4×4 Array
matrix= np.arange(16).reshape(4, 4)
extracted_grid = matrix[0:4:2, 1:4:2]
print(extracted_grid)


[[ 1  3]
 [ 9 11]]


In [ ]:
# Slice First Two Rows and First Two Columns of Second Set (4×4×3 Array)
arr_slice = np.arange(4 * 4 * 3).reshape(4, 4, 3)
sliced_block = arr_slice[1, 0:2, 0:2]
print(sliced_block)


[[12 13]
 [15 16]]


In [ ]:
#Replace Odd Numbers with -1 via For Loop
matrix_data = np.array([[23, 56, 78, 93], [71, 82, 13, 24]])

for i in range(matrix_data.shape[0]):
    for j in range(matrix_data.shape[1]):
        if matrix_data[i, j] % 2 != 0:
            matrix_data[i, j] = -1
print(matrix_data)


[[-1 56 78 -1]
 [-1 82 -1 24]]


In [ ]:
#Element-Wise Arithmetic (Addition and Multiplication)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

add_result = a + b
mul_result = a * b
print("Element-wise Addition:", add_result)
print("Element-wise Multiplication:", mul_result)


Element-wise Addition: [5 7 9]
Element-wise Multiplication: [ 4 10 18]


In [ ]:
#Compute Dot Product
arr1 = np.array([15, 20, 25])
arr2 = np.array([10, 40, 37])

dot_product = np.dot(arr1, arr2)
print("Dot Product:", dot_product)


Dot Product: 1875


In [18]:
#Get Indices of Non-Zero Elements
arr = np.array([1, 0, 2, 0, 3, 0, 4])
nonzero_indices = np.nonzero(arr)
print(nonzero_indices[0])


[0 2 4 6]
