In [3]:
#ques1
import numpy as np
arr = np.array([
    [6, -8, 73, -110],
    [np.nan, -8, 0, 94]
])
print("Original Array:")
print(arr)
print()
arr[np.isnan(arr)] = 0
print("Array after replacing NaN with 0:")
print(arr)
print()
transpose_arr = arr.T
print("Array after interchanging rows and columns:")
print(transpose_arr)

Original Array:
[[   6.   -8.   73. -110.]
 [  nan   -8.    0.   94.]]

Array after replacing NaN with 0:
[[   6.   -8.   73. -110.]
 [   0.   -8.    0.   94.]]

Array after interchanging rows and columns:
[[   6.    0.]
 [  -8.   -8.]
 [  73.    0.]
 [-110.   94.]]


In [33]:
#ques2
import numpy as np 
arr = np.array([
    [[6, -8], [73, -110]],
    [[14, -8], [0, 94]]
])
#array=np.arange(24).reshape(2,3,4)
#print(array)
#print('-------------------------')
new_arr = np.moveaxis(arr, 0, 1)
print("Array after Moving Axes:")
print(new_arr)

print("Shape after Moving Axes:")
print(new_arr.shape)



Array after Moving Axes:
[[[   6   -8]
  [  14   -8]]

 [[  73 -110]
  [   0   94]]]
Shape after Moving Axes:
(2, 2, 2)


In [ ]:
#ques3
import pandas as pd
data = {
    "Math": [94, 60, np.nan, 50],
    "English": [55, np.nan, 65, 85]
}
df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

df = df.fillna(df.mean())
print("\nDataFrame after replacing NaN with column average:")
print(df)

Original DataFrame:
   Math  English
0  94.0     55.0
1  60.0      NaN
2   NaN     65.0
3  50.0     85.0

DataFrame after replacing NaN with column average:
   Math    English
0  94.0  55.000000
1  60.0  68.333333
2  68.0  65.000000
3  50.0  85.000000


In [43]:
# QUES 4
arr = np.array([1,-5,25,-7,17,-2])

print("Original Array:")
print(arr)

# Replace negative values with 0
arr[arr < 0] = 0

print("\nArray after replacing negative values with 0:")
print(arr)

# Replace negative values with 0
arr = np.where(arr < 0, 0, arr)

print("\nArray after replacement:")
print(arr)

Original Array:
[ 1 -5 25 -7 17 -2]

Array after replacing negative values with 0:
[ 1  0 25  0 17  0]

Array after replacement:
[ 1  0 25  0 17  0]
