In [ ]:
#ques1
import numpy as np


# 1D array
arr1 = np.array([10, 20, 30])

# 2D array
arr2 = np.array([[1, 2, 3],
[4, 5, 6]])

print("1D Array:\n", arr1)
print("\n2D Array:\n", arr2)
print()
result = np.concatenate((arr2, arr1.reshape(1, 3)))

print(result)


1D Array:
 [10 20 30]

2D Array:
 [[1 2 3]
 [4 5 6]]

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]]


In [ ]:
#ques2
import numpy as np

# 2D array
arr = np.array([[1, 2, 3],
[4, 5, 6]])

print("Original Array:\n", arr)
print()
flat_arr = arr.ravel()

print("Flattened Array using ravel():", flat_arr)

Original Array:
 [[1 2 3]
 [4 5 6]]

Flattened Array using ravel(): [1 2 3 4 5 6]


In [25]:
#ques3
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Original Array:\n", arr)

rev = arr[::-1]

print("\nReversed Array:\n", rev)

Original Array:
 [10 20 30 40 50]

Reversed Array:
 [50 40 30 20 10]


In [ ]:
#ques4
import numpy as np

arr = np.array([[10, 5, 8],
[3, 15, 7]])

print("Array:\n", arr)
print("\nMax value:", np.max(arr))
print("Min value:", np.min(arr))
rows, cols = arr.shape

print("Rows:", rows)
print("Columns:", cols)
print()
print("\nFirst element:", arr[0][0]) 
print("Last element:", arr[1][2])      
print("Row 1:", arr[0])               
# Sum of values using for loop
total = 0

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        total += arr[i][j]

print("\nSum using loop:", total)         

Array:
 [[10  5  8]
 [ 3 15  7]]

Max value: 15
Min value: 3
Rows: 2
Columns: 3


First element: 10
Last element: 7
Row 1: [10  5  8]

Sum using loop: 48


In [30]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [36]:
#ques5
import numpy as np

arr = np.array([
    [[1, 2],
     [3, 4]],

    [[5, 6],
     [7, 8]]
])

print("3D Array:\n", arr)
print()
print("Shape:", arr.shape)
print("\nIterating using for loop:\n")

for i in range(arr.shape[0]):          
    for j in range(arr.shape[1]):      
        for k in range(arr.shape[2]):  
            print(arr[i][j][k])
print()
print("Iterating using nditer:")

for x in np.nditer(arr):
    print(x)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

Shape: (2, 2, 2)

Iterating using for loop:

1
2
3
4
5
6
7
8

Iterating using nditer:
1
2
3
4
5
6
7
8


In [43]:
#ques6
import numpy as np

# Two 2D arrays
arr1 = np.array([[3, 4],
[5, 6]])

arr2 = np.array([[1, 0],
[4, 8]])

print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)
avg = (arr1 + arr2) / 2
print("\nElement-wise Average:\n", avg)
s= np.concatenate((arr1, arr2))
mean_value = np.mean(s)

print("\nMean:", mean_value)
median_value = np.median(s)

print("Median:", median_value)
print()
values, counts = np.unique(s, return_counts=True)
most_frequent_value = values[np.argmax(counts)]

print("Most Frequent Value (Mode concept):", most_frequent_value)

Array 1:
 [[3 4]
 [5 6]]

Array 2:
 [[1 0]
 [4 8]]

Element-wise Average:
 [[2.  2. ]
 [4.5 7. ]]

Mean: 3.875
Median: 4.0

Most Frequent Value (Mode concept): 4
